version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=accounting_system
      - DB_PASSWORD=postgres_password
      - DB_PORT=5432
      # إذا كنت تريد استخدام Redis، قم بإلغاء التعليق على السطر التالي
      # - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=accounting_system
    ports:
      - "5432:5432"
    networks:
      - app-network

  # إذا كنت تريد استخدام Redis، قم بإلغاء التعليق على الخدمة التالية
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

  # إذا كنت تريد استخدام Nginx كبروكسي عكسي، قم بإلغاء التعليق على الخدمة التالية
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  # redis_data:
