#!/bin/bash

COMMAND=$(echo "$1" | tr 'A-Z' 'a-z')
APP_NAME="accounting-system"

case "$COMMAND" in
  start)
    pm2 start ecosystem.config.js
    ;;
  stop)
    pm2 stop "$APP_NAME"
    ;;
  restart)
    pm2 restart "$APP_NAME"
    ;;
  status)
    pm2 status "$APP_NAME"
    ;;
  update)
    git pull && pnpm install && pm2 restart "$APP_NAME"
    ;;
  delete)
    pm2 delete "$APP_NAME"
    ;;
  *)
    echo "Usage: NexAccount {Start|Stop|Restart|Status|Update|Delete}"
    exit 1
    ;;
 esac

